# Generated by Django 4.0.3 on 2022-03-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0012_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='uploads/post_videos'),
        ),
    ]
