# Generated by Django 4.0.3 on 2022-03-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0013_post_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('video', models.FileField(blank=True, null=True, upload_to='uploads/post_videos')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.ManyToManyField(blank=True, null=True, to='show.video'),
        ),
    ]
