# Generated by Django 4.0.3 on 2022-03-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0014_video_remove_post_video_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.ManyToManyField(blank=True, to='show.video'),
        ),
    ]
